// website/src/source-examples/quickstart/App.tsx
import { useMolecule } from "bunshi/react";
import React from "react";
import { ResizeMolecule } from "./molecules";

export default function Resized() {
  const observer = useMolecule(ResizeMolecule);
  const style = {
    border: "2px solid",
    padding: "20px",
    width: "300px",
    resize: "both",
    overflow: "auto",
  } as const;
  return (
    <div style={style} ref={(el) => observer.observe(el)}>
      My size is being watched.
    </div>
  );
}

// website/src/source-examples/quickstart/App.vue
<script setup>
import { useMolecule } from "bunshi/vue";
import { ref, onMounted, onUnmounted } from "vue";
import { ResizeMolecule } from "./molecules";

const observer = useMolecule(ResizeMolecule);
const root = ref(null);
onMounted(() => observer.observe(root.value));
onUnmounted(() => observer.unobserve(root.value));
</script>
<style>
.resize {
  border: 2px solid;
  padding: 20px;
  width: 300px;
  resize: both;
  overflow: auto;
}
</style>
<template>
  <div ref="root" class="resize">My size is being watched.</div>
</template>
